### ISSUE TITLE
有完整的sql？ 就是包含你的数据的 能上传一份？

### ISSUE THREAD

**Issue by Rainwind1995** [huangyilong2000/community#2]

**Comment by huang-yilong** [comment]
都在sql文件夹

**Comment by huang-yilong** [comment]
在牛客网也有，免费

**Comment by Rainwind1995** [comment]
你给的我看了下和官方给的一样 都只有几个基础的表 但是没有数据呀





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Trydamere/community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上8:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Trydamere/community] 有完整的sql？ 就是包含你的数据的 能上传一份？ (Issue #2)





 
都在sql文件夹

**Comment by huang-yilong** [comment]
数据在init_data.sql

**Comment by Rainwind1995** [comment]
谢谢 我找到了&nbsp; 打扰你了 真不好意思


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Trydamere/community"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Trydamere/community] 有完整的sql？ 就是包含你的数据的 能上传一份？ (Issue #2)





 
数据在init_data.sql
